#!/usr/bin/env python3
"""Bundles sounds/*.ogg into web/sounds.js, so the game can load them from any page, file:// included.

Run it after adding or changing a sound:  python3 tools/pack_sounds.py
"""
import base64, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC, OUT = os.path.join(ROOT, 'sounds'), os.path.join(ROOT, 'web', 'sounds.js')

names = sorted(f for f in os.listdir(SRC) if f.endswith('.ogg'))
with open(OUT, 'w') as out:
    out.write('// Generated by tools/pack_sounds.py from sounds/*.ogg (credits in CREDITS.md). Do not edit.\n')
    out.write('window.SOUNDS = {\n')
    for n in names:
        with open(os.path.join(SRC, n), 'rb') as f:
            out.write(f'"{n[:-4]}":"{base64.b64encode(f.read()).decode()}",\n')
    out.write('};\n')
print(f'{len(names)} sounds -> {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT) // 1024} KB)')
